# Generated by Django 2.2.7 on 2020-02-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('added_ts', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField()),
                ('article_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
