# Generated by Django 2.2.7 on 2020-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200214_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
