# Generated by Django 2.2.7 on 2020-02-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200214_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(max_length=255),
        ),
    ]
