# Generated by Django 2.2.7 on 2020-02-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
