# Generated by Django 2.2.7 on 2020-02-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_category_feed_feed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'Feeds'},
        ),
    ]
